services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=dashboard'
      - 'POSTGRES_PASSWORD=postgrespw'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'

  springboot-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dashboard
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgrespw
    volumes:
      - .:/app
    depends_on:
      - postgres
